Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2022-12, with the labels that each got.

#14 Merge into live 12/12/2022
  .openpublishing.publish.config.json
Labels: do-not-merge, review-team-triage

#16 Refactor manifests.md
  vcpkg/TOC.yml
  vcpkg/commands/common-options.md
  vcpkg/commands/install.md
  vcpkg/commands/update-baseline.md
  vcpkg/contributing/pr-review-checklist.md
  vcpkg/docfx.json
  vcpkg/maintainers/control-files.md
  vcpkg/maintainers/functions/vcpkg_fail_port_install.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/classic-mode.md
  vcpkg/users/config-environment.md
  vcpkg/users/examples/versioning.getting-started.md
  vcpkg/users/manifests.md
  vcpkg/users/registries.md
  vcpkg/users/triplets.md
  vcpkg/users/versioning.md
Labels: do-not-merge, needs-human-review

#17 Sync with vcpkg changes to docs/ in 9074f833496ebd1b3e050f62568b9bba014f2d17
  vcpkg/contributing/vcpkg_tool_release_process.md
  vcpkg/examples/packaging-github-repos.md
Labels: do-not-merge, needs-human-review

#19 Sync with vcpkg changes to docs/ in 9074f833496ebd1b3e050f62568b9bba014f2d17
  vcpkg/contributing/maintainer-guide.md
  vcpkg/contributing/vcpkg_tool_release_process.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
Labels: do-not-merge, qualifies-for-auto-merge

#20 Fix broken schema links
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
Labels: do-not-merge, qualifies-for-auto-merge

#22 Port PR Microsoft/vcpkg#27883 and rewrite binarycaching.md
  vcpkg/maintainers/functions/vcpkg_cmake_configure.md
  vcpkg/maintainers/functions/vcpkg_cmake_install.md
  vcpkg/users/assetcaching.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/config-environment.md
  vcpkg/users/triplets.md
Labels: do-not-merge, needs-human-review

#21 Migration of https://github.com/microsoft/vcpkg/pull/28189
  vcpkg/maintainers/functions/vcpkg_build_msbuild.md
  vcpkg/maintainers/functions/vcpkg_install_msbuild.md
Labels: do-not-merge, needs-human-review
