Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2023-02, with the labels that each got.

#29 Migrate PR Microsoft/vcpkg#27309
  vcpkg/commands/export.md
Labels: do-not-merge, needs-human-review

#25 Transfer Microsoft/vcpkg#27686
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/users/registries.md
Labels: do-not-merge, needs-human-review

#27 Adding a dev container specification
  .devcontainer/devcontainer.json
Labels: do-not-merge, needs-human-review, review-team-triage

#30 Push to live
  .devcontainer/devcontainer.json
  .gitignore
  vcpkg/TOC.yml
  vcpkg/commands/export.md
  vcpkg/maintainers/functions/vcpkg_build_msbuild.md
  vcpkg/maintainers/functions/vcpkg_cmake_configure.md
  vcpkg/maintainers/functions/vcpkg_cmake_install.md
  vcpkg/maintainers/functions/vcpkg_install_msbuild.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/assetcaching.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/config-environment.md
  vcpkg/users/registries.md
  vcpkg/users/triplets.md
Labels: do-not-merge

#32 Migrate Microsoft/vcpkg#29209
  vcpkg/contributing/maintainer-guide.md
Labels: do-not-merge, qualifies-for-auto-merge

#38 Synchronize changes from Microsoft/vcpkg until Feb 16
  vcpkg/TOC.yml
  vcpkg/examples/adding-usage.md
  vcpkg/maintainers/functions/vcpkg_execute_required_process.md
  vcpkg/maintainers/functions/vcpkg_from_git.md
Labels: do-not-merge, needs-human-review

#31 [vcpkg docs] Add depend-info command documentation
  vcpkg/commands/depend-info.md
Labels: do-not-merge, Change sent to author, vcpkg/prod

#40 Fix depend-info. Add ref from vcpkg_from_git to authentication.
  vcpkg/commands/depend-info.md
  vcpkg/maintainers/functions/vcpkg_from_git.md
Labels: do-not-merge, qualifies-for-auto-merge

#41 Fix header & breadcrumbs
  vcpkg/docfx.json
Labels: do-not-merge, needs-human-review, review-team-triage
