Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2023-08, with the labels that each got.

#120 Push to live (8.7.2023)
  vcpkg/github-integration.md
Labels: do-not-merge, Change sent to author, vcpkg/prod

#113 Add docs for `vcpkg edit`
  vcpkg/TOC.yml
  vcpkg/commands/edit.md
Labels: do-not-merge, needs-human-review

#109 Add docs for `vcpkg env`
  vcpkg/TOC.yml
  vcpkg/commands/env.md
Labels: do-not-merge, needs-human-review

#75 Add Xbox triplet doc page
  vcpkg/users/platforms/xbox.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#103 Restore removed articles
  vcpkg/contributing/vcpkg_catalog_release_process.md
  vcpkg/contributing/vcpkg_tool_release_process.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#116 [vcpkg export] manifest mode
  vcpkg/commands/export.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#121 Revert "[vcpkg export] manifest mode"
  vcpkg/commands/export.md
Labels: do-not-merge, qualifies-for-auto-merge

#122 Update export docs
  vcpkg/commands/export.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#138 Create get started node and add skeleton overview page
  vcpkg/get_started/overview.md
Labels: do-not-merge, needs-human-review

#136 Document "Reference/Commands/vcpkg owns"
  vcpkg/TOC.yml
  vcpkg/commands/owns.md
Labels: do-not-merge, needs-human-review

#135 Document "Reference/Commands/vcpkg hash"
  vcpkg/TOC.yml
  vcpkg/commands/hash.md
Labels: do-not-merge, needs-human-review

#140 Missing VCPKG_TARGET_IS_IOS variable
  vcpkg/maintainers/variables.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#129 Document "Reference/Commands/vcpkg contact"
  vcpkg/TOC.yml
  vcpkg/commands/contact.md
Labels: do-not-merge, needs-human-review

#114 Add docs for requested features with platform expressions
  vcpkg/reference/vcpkg-json.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#134 Document "Reference/Commands/vcpkg format-manifest"
  vcpkg/TOC.yml
  vcpkg/commands/format-manifest.md
Labels: do-not-merge, needs-human-review

#128 Document "Reference/Commands/vcpkg x-add-version"
  vcpkg/TOC.yml
  vcpkg/commands/add-version.md
  vcpkg/users/versioning.md
Labels: do-not-merge, needs-human-review

#117 Document "Reference/Commands/vcpkg create"
  vcpkg/TOC.yml
  vcpkg/commands/create.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod
