Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2023-10, with the labels that each got.

#168 Multiple Articles: Getting Started: CMake / CLI / Visual Studio
  vcpkg/TOC.yml
  vcpkg/examples/snippets/get-started/CMakeLists.txt
  vcpkg/examples/snippets/get-started/CMakePresets.json
  vcpkg/examples/snippets/get-started/main.cpp
  vcpkg/get_started/get-started-vs.md
  vcpkg/get_started/get-started.md
  vcpkg/get_started/includes/setup-vcpkg.md
  vcpkg/get_started/setup-vcpkg.md
  vcpkg/resources/get_started/visual-studio-create-project.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup.png
  vcpkg/resources/get_started/visual-studio-helloworld-output.png
  vcpkg/resources/get_started/visual-studio-name-project.png
  vcpkg/resources/get_started/visual-studio-run-project.png
Labels: do-not-merge, needs-human-review

#130 Document binary caching (multiple articles)
  vcpkg/TOC.yml
  vcpkg/consume/binary-caching-default.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-github-packages.md
  vcpkg/consume/binary-caching-local.md
  vcpkg/consume/binary-caching-nuget.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/users/binarycaching.md
Labels: do-not-merge, needs-human-review

#175 Multiple articles: Re-work article pivots
  vcpkg/consume/binary-caching-default.md
  vcpkg/consume/binary-caching-github-packages.md
  vcpkg/consume/binary-caching-local.md
  vcpkg/consume/binary-caching-nuget.md
  vcpkg/get_started/get-started-vs.md
  vcpkg/get_started/get-started.md
  vcpkg/get_started/includes/setup-vcpkg.md
  vcpkg/resources/get_started/visual-studio-create-project.png
  vcpkg/resources/get_started/visual-studio-developer-cmd.png
  vcpkg/resources/get_started/visual-studio-developer-powershell.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup-cmd.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup-powershell.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup.png
  vcpkg/resources/get_started/visual-studio-name-project.png
  vcpkg/resources/get_started/visual-studio-run-project.png
  vcpkg/zone-pivot-groups.json
Labels: do-not-merge, needs-human-review, review-team-triage

#177 Use target_Xxx rather than Xxx in examples.
  vcpkg/examples/installing-and-using-packages.md
  vcpkg/users/buildsystems/cmake-integration.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#179 Push to `live`
  vcpkg/TOC.yml
  vcpkg/concepts/ports.md
  vcpkg/consume/binary-caching-default.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-github-packages.md
  vcpkg/consume/binary-caching-local.md
  vcpkg/consume/binary-caching-nuget.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/consume/lock-package-versions.md
  vcpkg/examples/installing-and-using-packages.md
  vcpkg/examples/snippets/get-started/CMakeLists.txt
  vcpkg/examples/snippets/get-started/CMakePresets.json
  vcpkg/examples/snippets/get-started/main.cpp
  vcpkg/get_started/get-started-vs.md
  vcpkg/get_started/get-started.md
  vcpkg/get_started/includes/setup-vcpkg.md
  vcpkg/get_started/setup-vcpkg.md
  vcpkg/resources/get_started/visual-studio-create-project.png
  vcpkg/resources/get_started/visual-studio-developer-cmd.png
  vcpkg/resources/get_started/visual-studio-developer-powershell.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup-cmd.png
  vcpkg/resources/get_started/visual-studio-environment-variable-setup-powershell.png
  vcpkg/resources/get_started/visual-studio-helloworld-output.png
  vcpkg/resources/get_started/visual-studio-name-project.png
  vcpkg/resources/get_started/visual-studio-run-project.png
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/zone-pivot-groups.json
Labels: do-not-merge, review-team-triage

#172 Getting started guide for MSBuild/Visual Studio
  vcpkg/TOC.yml
  vcpkg/get_started/get-started-msbuild.md
  vcpkg/resources/get_started/visual-studio-create-project-msbuild.png
  vcpkg/resources/get_started/visual-studio-manifest-msbuild.png
  vcpkg/resources/get_started/visual-studio-msbuild-output.png
  vcpkg/resources/get_started/visual-studio-msbuild-project.png
  vcpkg/resources/get_started/visual-studio-name-project-msbuild.png
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#171 Port overlays documentation
  vcpkg/TOC.yml
  vcpkg/concepts/overlay-ports.md
  vcpkg/resources/ports-overlay-example.png
Labels: do-not-merge, needs-human-review

#162 Reference: Installation directory layout
  vcpkg/TOC.yml
  vcpkg/reference/installation-tree-layout.md
Labels: do-not-merge, needs-human-review

#152 Binary caching troubleshooting guide
  includes/debug.md
  vcpkg/TOC.yml
  vcpkg/users/binarycaching-troubleshooting.md
  vcpkg/users/binarycaching.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#183 vcpkg overview page and article topic metadata fixes
  vcpkg/TOC.yml
  vcpkg/about/faq.md
  vcpkg/about/privacy.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/contributing/cmake-guidelines.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/contributing/pr-review-checklist.md
  vcpkg/examples/asset-caching-source-nuget.md
  vcpkg/examples/packaging-github-repos.md
  vcpkg/examples/packaging-zipfiles.md
  vcpkg/examples/patching.md
  vcpkg/get_started/overview.md
  vcpkg/github-integration.md
  vcpkg/maintainers/authoring-script-ports.md
  vcpkg/maintainers/control-files.md
  vcpkg/maintainers/handling-usage-files.md
  vcpkg/maintainers/registries.md
  vcpkg/maintainers/variables.md
  vcpkg/reference/installation-tree-layout.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/assetcaching.md
  vcpkg/users/authentication.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/manual-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/classic-mode.md
  vcpkg/users/config-environment.md
  vcpkg/users/examples/overlay-triplets-linux-dynamic.md
  vcpkg/users/examples/selecting-llvm-features.md
  vcpkg/users/host-dependencies.md
  vcpkg/users/manifests.md
  vcpkg/users/platforms/android.md
  vcpkg/users/platforms/mingw.md
  vcpkg/users/platforms/xbox.md
  vcpkg/users/registries.md
  vcpkg/users/triplets.md
  vcpkg/users/versioning.concepts.md
  vcpkg/users/versioning.md
Labels: do-not-merge, needs-human-review

#180 Push to `live`
  includes/debug.md
  vcpkg/TOC.yml
  vcpkg/about/faq.md
  vcpkg/about/privacy.md
  vcpkg/concepts/overlay-ports.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/contributing/cmake-guidelines.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/contributing/pr-review-checklist.md
  vcpkg/examples/asset-caching-source-nuget.md
  vcpkg/examples/packaging-github-repos.md
  vcpkg/examples/packaging-zipfiles.md
  vcpkg/examples/patching.md
  vcpkg/get_started/get-started-msbuild.md
  vcpkg/get_started/overview.md
  vcpkg/github-integration.md
  vcpkg/maintainers/authoring-script-ports.md
  vcpkg/maintainers/control-files.md
  vcpkg/maintainers/handling-usage-files.md
  vcpkg/maintainers/registries.md
  vcpkg/maintainers/variables.md
  vcpkg/reference/installation-tree-layout.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/resources/get_started/visual-studio-create-project-msbuild.png
  vcpkg/resources/get_started/visual-studio-manifest-msbuild.png
  vcpkg/resources/get_started/visual-studio-msbuild-output.png
  vcpkg/resources/get_started/visual-studio-msbuild-project.png
  vcpkg/resources/get_started/visual-studio-name-project-msbuild.png
  vcpkg/resources/ports-overlay-example.png
  vcpkg/users/assetcaching.md
  vcpkg/users/authentication.md
  vcpkg/users/binarycaching-troubleshooting.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/manual-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/classic-mode.md
  vcpkg/users/config-environment.md
  vcpkg/users/examples/overlay-triplets-linux-dynamic.md
  vcpkg/users/examples/selecting-llvm-features.md
  vcpkg/users/host-dependencies.md
  vcpkg/users/manifests.md
  vcpkg/users/platforms/android.md
  vcpkg/users/platforms/mingw.md
  vcpkg/users/platforms/xbox.md
  vcpkg/users/registries.md
  vcpkg/users/triplets.md
  vcpkg/users/versioning.concepts.md
  vcpkg/users/versioning.md
Labels: do-not-merge

#192 Add build system integration concepts
  vcpkg/TOC.yml
  vcpkg/concepts/build-system-integration.md
Labels: do-not-merge, needs-human-review

#191 Add concepts/registries and update links
  .openpublishing.redirection.json
  vcpkg/TOC.yml
  vcpkg/commands/common-options.md
  vcpkg/commands/update-baseline.md
  vcpkg/concepts/overlay-ports.md
  vcpkg/concepts/package-name-resolution.md
  vcpkg/concepts/registries.md
  vcpkg/consume/git-registries.md
  vcpkg/consume/manifest-mode.md
  vcpkg/get_started/overview.md
  vcpkg/maintainers/registries.md
  vcpkg/produce/publish-to-a-git-registry.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
Labels: do-not-merge, needs-human-review

#190 Add asset caching tutorial and split reference and concepts
  vcpkg/TOC.yml
  vcpkg/concepts/asset-caching.md
  vcpkg/consume/asset-caching.md
  vcpkg/users/assetcaching.md
Labels: do-not-merge, needs-human-review

#193 Updated vcpkg overview page based on feedback from ras0219-msft
  vcpkg/get_started/overview.md
Labels: do-not-merge, qualifies-for-auto-merge

#184 Add manifest mode concept article
  vcpkg/TOC.yml
  vcpkg/concepts/manifest-mode.md
  vcpkg/users/manifests.md
Labels: do-not-merge, needs-human-review

#173 Document "Getting Started/create and publish packages"
  vcpkg/get_started/get-started-adding-to-registry.md
  vcpkg/get_started/get-started-packaging.md
  vcpkg/get_started/get-started.md
Labels: do-not-merge, needs-human-review

#194 Add tutorial for patching and overlay ports
  vcpkg/TOC.yml
  vcpkg/consume/install-locally-modified-package.md
Labels: do-not-merge, needs-human-review

#185 Update index cards
  vcpkg/index.yml
Labels: do-not-merge, Change sent to author, vcpkg/prod

#196 Added creating/publishing tutorials to get started node and fixed some typos
  vcpkg/TOC.yml
  vcpkg/get_started/get-started-adding-to-registry.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#195 Sync to live
  .openpublishing.redirection.json
  vcpkg/TOC.yml
  vcpkg/commands/common-options.md
  vcpkg/commands/update-baseline.md
  vcpkg/concepts/asset-caching.md
  vcpkg/concepts/build-system-integration.md
  vcpkg/concepts/manifest-mode.md
  vcpkg/concepts/overlay-ports.md
  vcpkg/concepts/package-name-resolution.md
  vcpkg/concepts/registries.md
  vcpkg/concepts/triplets.md
  vcpkg/consume/asset-caching.md
  vcpkg/consume/boost-versions.md
  vcpkg/consume/git-registries.md
  vcpkg/consume/install-locally-modified-package.md
  vcpkg/consume/manifest-mode.md
  vcpkg/get_started/get-started-adding-to-registry.md
  vcpkg/get_started/get-started-packaging.md
  vcpkg/get_started/get-started.md
  vcpkg/get_started/overview.md
  vcpkg/index.yml
  vcpkg/maintainers/registries.md
  vcpkg/produce/publish-to-a-git-registry.md
  vcpkg/reference/vcpkg-configuration-json.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/assetcaching.md
  vcpkg/users/config-environment.md
  vcpkg/users/manifests.md
  vcpkg/users/triplets.md
Labels: do-not-merge

#197 Homepage updates
  vcpkg/index.yml
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#198 Homepage updates (#197)
  vcpkg/index.yml
Labels: do-not-merge, Change sent to author, vcpkg/prod

#186 Add glossary of terms
  vcpkg/TOC.yml
  vcpkg/concepts/glossary.md
Labels: do-not-merge, needs-human-review

#199 Fixed typo in ToC
  vcpkg/TOC.yml
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#202 some edits
  vcpkg/get_started/overview.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod
