Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2023-09, with the labels that each got.

#142 Add docs for --x-cmake-debug and --x-cmake-configure-debug
  vcpkg/commands/common-options.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#139 Add background information on how toolchain leads to dependency acquisition
  vcpkg/users/buildsystems/cmake-integration.md
Labels: do-not-merge, Change sent to author, vcpkg/prod

#127 Docs for vcpkg-msbuild
  vcpkg/maintainers/functions/vcpkg_build_msbuild.md
  vcpkg/maintainers/functions/vcpkg_clean_msbuild.md
  vcpkg/maintainers/functions/vcpkg_install_msbuild.md
  vcpkg/maintainers/functions/vcpkg_msbuild_install.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#115 Document what users are supposed to do when text licenses are unavailable.
  vcpkg/contributing/maintainer-guide.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#144 Change `vcpkg_msbuild_install` usage
  vcpkg/maintainers/functions/vcpkg_msbuild_install.md
Labels: do-not-merge, qualifies-for-auto-merge

#106 Document "Reference/Commands/vcpkg new"
  vcpkg/TOC.yml
  vcpkg/commands/new.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#146 Fix `vcpkg new` metadata and links
  vcpkg/commands/new.md
Labels: do-not-merge, qualifies-for-auto-merge

#145 Push main to live (09/11/2023)
  vcpkg/TOC.yml
  vcpkg/commands/add-version.md
  vcpkg/commands/add.md
  vcpkg/commands/create.md
  vcpkg/commands/edit.md
  vcpkg/commands/env.md
  vcpkg/commands/export.md
  vcpkg/commands/format-manifest.md
  vcpkg/commands/hash.md
  vcpkg/commands/new.md
  vcpkg/commands/owns.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/contributing/vcpkg_catalog_release_process.md
  vcpkg/contributing/vcpkg_tool_release_process.md
  vcpkg/get_started/overview.md
  vcpkg/maintainers/functions/vcpkg_build_msbuild.md
  vcpkg/maintainers/functions/vcpkg_clean_msbuild.md
  vcpkg/maintainers/functions/vcpkg_install_msbuild.md
  vcpkg/maintainers/functions/vcpkg_msbuild_install.md
  vcpkg/maintainers/variables.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/platforms/xbox.md
  vcpkg/users/versioning.md
Labels: do-not-merge

#147 Add resources links
  vcpkg/TOC.yml
  vcpkg/resources/support-channels.md
Labels: do-not-merge, needs-human-review

#148 Get Started: Install vcpkg / Set up zone pivots
  .openpublishing.publish.config.json
  vcpkg/docfx.json
  vcpkg/get_started/setup-vcpkg.md
  vcpkg/zone-pivot-groups.json
Labels: do-not-merge, needs-human-review

#151 Fix a typo
  vcpkg/commands/export.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#150 [Multiple articles] Restructure table of contents
  vcpkg/TOC.yml
  vcpkg/users/assetcaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
Labels: do-not-merge, needs-human-review

#124 Document "Consume packages/Install a dependency from a manifest file"
  .openpublishing.redirection.json
  vcpkg/TOC.yml
  vcpkg/consume/manifest-mode.md
  vcpkg/examples/manifest-mode-cmake.md
  vcpkg/resources/vs-enable-vcpkg-manifest.png
Labels: do-not-merge, needs-human-review

#112 Tutorial: Publish packages to a private vcpkg registry using Git
  vcpkg/TOC.yml
  vcpkg/produce/publish-to-a-git-registry.md
Labels: do-not-merge, needs-human-review

#126 Document "Consume packages/Install a dependency from the command-line"
  vcpkg/TOC.yml
  vcpkg/consume/classic-mode.md
  vcpkg/consume/manifest-mode.md
  vcpkg/examples/installing-and-using-packages.md
Labels: do-not-merge, needs-human-review

#154 Rearrange the "Consume Packages" section in the table of contents
  vcpkg/TOC.yml
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#156 Rearrange "Produce Packages" section in table of contents
  vcpkg/TOC.yml
  vcpkg/examples/adding-usage.md
Labels: do-not-merge, needs-human-review

#157 Add "Install vcpkg" to ToC
  vcpkg/TOC.yml
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#149 Document "Reference/Commands/vcpkg help
  vcpkg/TOC.yml
  vcpkg/commands/help.md
Labels: do-not-merge, needs-human-review

#155 Tutorial: Install packages from a Git-based registry
  vcpkg/TOC.yml
  vcpkg/consume/git-registries.md
  vcpkg/consume/snippets/git-registries/CMakeLists.txt
  vcpkg/consume/snippets/git-registries/main.cpp
  vcpkg/users/registries.md
Labels: do-not-merge, needs-human-review

#111 Tutorial: Authenticate to private Git registries in your GitHub Actions workflows
  .markdownlint.jsonc
  vcpkg/TOC.yml
  vcpkg/consume/gha-authentication.md
Labels: do-not-merge, needs-human-review

#153 Tutorial: Install specific versions of your dependencies
  vcpkg/TOC.yml
  vcpkg/consume/lock-package-versions.md
  vcpkg/consume/snippets/versioning-cmakelists.txt
  vcpkg/consume/snippets/versioning-main.cpp
  vcpkg/users/examples/modify-baseline-to-pin-old-boost.md
  vcpkg/users/examples/versioning.getting-started.md
  vcpkg/users/versioning.md
Labels: do-not-merge

#160 Merge `next-release` into `main`
  vcpkg/TOC.yml
  vcpkg/commands/common-options.md
  vcpkg/commands/contact.md
Labels: do-not-merge, needs-human-review

#164 Fix incorrect link
  vcpkg/consume/lock-package-versions.md
Labels: do-not-merge, qualifies-for-auto-merge

#165 Fixed typo in faq.md
  vcpkg/about/faq.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#166 Change default content topic to reference in docfx.json
  vcpkg/docfx.json
Labels: do-not-merge, needs-human-review, review-team-triage

#167 Miscelaneous fixes
  vcpkg/TOC.yml
  vcpkg/commands/common-options.md
  vcpkg/commands/help.md
  vcpkg/consume/classic-mode.md
  vcpkg/consume/gha-authentication.md
  vcpkg/consume/git-registries.md
  vcpkg/consume/lock-package-versions.md
  vcpkg/consume/manifest-mode.md
  vcpkg/get_started/setup-vcpkg.md
  vcpkg/users/assetcaching.md
Labels: do-not-merge, needs-human-review

#169 Fix links
  vcpkg/consume/git-registries.md
Labels: do-not-merge, qualifies-for-auto-merge

#161 Push to `live`
  .markdownlint.jsonc
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
  vcpkg/TOC.yml
  vcpkg/about/faq.md
  vcpkg/commands/common-options.md
  vcpkg/commands/contact.md
  vcpkg/commands/export.md
  vcpkg/commands/help.md
  vcpkg/consume/classic-mode.md
  vcpkg/consume/gha-authentication.md
  vcpkg/consume/git-registries.md
  vcpkg/consume/lock-package-versions.md
  vcpkg/consume/manifest-mode.md
  vcpkg/consume/snippets/git-registries/CMakeLists.txt
  vcpkg/consume/snippets/git-registries/main.cpp
  vcpkg/consume/snippets/versioning-cmakelists.txt
  vcpkg/consume/snippets/versioning-main.cpp
  vcpkg/docfx.json
  vcpkg/examples/adding-usage.md
  vcpkg/examples/installing-and-using-packages.md
  vcpkg/examples/manifest-mode-cmake.md
  vcpkg/get_started/setup-vcpkg.md
  vcpkg/produce/publish-to-a-git-registry.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/resources/support-channels.md
  vcpkg/resources/vs-enable-vcpkg-manifest.png
  vcpkg/users/assetcaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/examples/modify-baseline-to-pin-old-boost.md
  vcpkg/users/examples/versioning.getting-started.md
  vcpkg/users/registries.md
  vcpkg/users/versioning.md
  vcpkg/zone-pivot-groups.json
Labels: do-not-merge

#158 Concept: Ports
  vcpkg/TOC.yml
  vcpkg/concepts/ports.md
Labels: do-not-merge, needs-human-review

#170 Add PowerShell command to inspect the baseline
  vcpkg/consume/lock-package-versions.md
Labels: do-not-merge, qualifies-for-auto-merge
