Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2023-04, with the labels that each got.

#51 Fixed link to Creating Registries
  vcpkg/users/registries.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#55 fix broken link
  vcpkg/users/manifests.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#52 Add docs for upgrade/update
  vcpkg/TOC.yml
  vcpkg/commands/list.md
  vcpkg/commands/update.md
  vcpkg/commands/upgrade.md
Labels: do-not-merge, needs-human-review

#56 how to diable default features
  vcpkg/users/manifests.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#58 Push to live 4/10/23
  vcpkg/TOC.yml
  vcpkg/commands/list.md
  vcpkg/commands/update.md
  vcpkg/commands/upgrade.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/manifests.md
  vcpkg/users/registries.md
  vcpkg/users/triplets.md
Labels: do-not-merge

#64 Update vcpkg-json.md
  vcpkg/reference/vcpkg-json.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#65 Assorted small doc fixes
  vcpkg/commands/common-options.md
  vcpkg/commands/export.md
  vcpkg/commands/install.md
  vcpkg/commands/search.md
  vcpkg/commands/update-baseline.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/manual-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/config-environment.md
  vcpkg/users/triplets.md
Labels: do-not-merge, needs-human-review

#66 Rewrite manifest-mode-cmake example to avoid Classic Mode
  vcpkg/examples/manifest-mode-cmake.md
  vcpkg/examples/snippets/manifest-mode-cmake/CMakeLists.txt
  vcpkg/examples/snippets/manifest-mode-cmake/main.cxx
  vcpkg/examples/snippets/manifest-mode-cmake/vcpkg.json
Labels: do-not-merge, needs-human-review

#67 Push to live 20230419
  vcpkg/commands/common-options.md
  vcpkg/commands/export.md
  vcpkg/commands/install.md
  vcpkg/commands/search.md
  vcpkg/commands/update-baseline.md
  vcpkg/examples/manifest-mode-cmake.md
  vcpkg/examples/packaging-github-repos.md
  vcpkg/examples/packaging-zipfiles.md
  vcpkg/examples/snippets/manifest-mode-cmake/CMakeLists.txt
  vcpkg/examples/snippets/manifest-mode-cmake/main.cxx
  vcpkg/examples/snippets/manifest-mode-cmake/vcpkg.json
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/binarycaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/manual-integration.md
  vcpkg/users/buildsystems/msbuild-integration.md
  vcpkg/users/config-environment.md
  vcpkg/users/triplets.md
Labels: do-not-merge

#61 Add docs for asset caching x-script usage
  vcpkg/TOC.yml
  vcpkg/examples/asset-caching-source-nuget.md
  vcpkg/users/assetcaching.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod

#72 Fix warning in vcpkg_from_bitbucket
  vcpkg/maintainers/functions/vcpkg_from_bitbucket.md
Labels: do-not-merge, qualifies-for-auto-merge

#71 Add CMake Presets to the CMake Integration docs
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/snippets/cmake-integration/CMakePresets.json
  vcpkg/users/buildsystems/snippets/cmake-integration/CMakeUserPresets.json
Labels: do-not-merge, needs-human-review

#73 Corrected platform expression
  vcpkg/reference/vcpkg-json.md
Labels: do-not-merge, qualifies-for-auto-merge, Change sent to author, vcpkg/prod

#69 Fix error
  vcpkg/docfx.json
Labels: do-not-merge, needs-human-review, review-team-triage

#74 Push to live 2023/04/25
  vcpkg/TOC.yml
  vcpkg/docfx.json
  vcpkg/examples/asset-caching-source-nuget.md
  vcpkg/maintainers/functions/vcpkg_from_bitbucket.md
  vcpkg/reference/vcpkg-json.md
  vcpkg/users/assetcaching.md
  vcpkg/users/buildsystems/cmake-integration.md
  vcpkg/users/buildsystems/snippets/cmake-integration/CMakePresets.json
  vcpkg/users/buildsystems/snippets/cmake-integration/CMakeUserPresets.json
Labels: do-not-merge

#62 Update Android docs
  vcpkg/users/platforms/android.md
Labels: do-not-merge, needs-human-review, Change sent to author, vcpkg/prod
