Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2025-04, with the labels that each got.

#344 Replay VCPKG_FIND_PACKAGE_
  vcpkg/users/buildsystems/cmake-integration.md
Labels: do-not-merge, Change sent to author, review-team-triage, vcpkg/svc

#465 Change FAQ entry for customizing compiler flags
  vcpkg/about/faq.md
Labels: do-not-merge, review-team-triage

#468 Add MAYBE_UNUSED_VARIABLES entry in maintainers guide
  vcpkg/contributing/maintainer-guide.md
Labels: do-not-merge, review-team-triage

#457 Add Offline Guide, referencing existing tutorials for export and asset caching.
  vcpkg/TOC.yml
  vcpkg/concepts/offline.md
  vcpkg/produce/export-compiled-dependencies.md
  vcpkg/users/assetcaching.md
Labels: do-not-merge, needs-human-review, review-team-triage

#471 Sort Concepts ToC entries alphabetically
  vcpkg/TOC.yml
Labels: do-not-merge, needs-human-review, review-team-triage

#472 Push to live 4/17/2025
  vcpkg/TOC.yml
  vcpkg/about/faq.md
  vcpkg/concepts/offline.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/get_started/get-started-packaging.md
  vcpkg/maintainers/handling-usage-files.md
  vcpkg/produce/export-compiled-dependencies.md
  vcpkg/users/assetcaching.md
  vcpkg/users/buildsystems/cmake-integration.md
Labels: do-not-merge, review-team-triage
