Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2025-03, with the labels that each got.

#454 Delete documentation for broken export backends.
  vcpkg/commands/export.md
  vcpkg/users/platforms/android.md
Labels: do-not-merge, needs-human-review, review-team-triage

#456 Update windows symbol export hint
  vcpkg/contributing/maintainer-guide.md
Labels: do-not-merge

#459 Rework asset caching conceptual article
  vcpkg/TOC.yml
  vcpkg/concepts/asset-caching.md
Labels: do-not-merge, needs-human-review, review-team-triage

#460 Asset caching tutorial improvements
  vcpkg/consume/asset-caching.md
  vcpkg/examples/asset-caching-source-nuget.md
Labels: do-not-merge, needs-human-review, review-team-triage

#461 Authenticate to NuGet package feeds
  vcpkg/TOC.yml
  vcpkg/consume/third-party-authentication.nuget.md
Labels: do-not-merge, needs-human-review, review-team-triage

#464 03/31 push to live
  .github/ISSUE_TEMPLATE/z-learn-feedback-tool.yml
  vcpkg/TOC.yml
  vcpkg/commands/export.md
  vcpkg/concepts/asset-caching.md
  vcpkg/consume/asset-caching.md
  vcpkg/consume/third-party-authentication.nuget.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/examples/asset-caching-source-nuget.md
  vcpkg/users/platforms/android.md
Labels: do-not-merge, review-team-triage

#463 Revise usage and copyright instructions
  vcpkg/get_started/get-started-packaging.md
  vcpkg/maintainers/handling-usage-files.md
Labels: do-not-merge, review-team-triage
