Repository MicrosoftDocs/vcpkg-docs, pull requests merged in 2025-05, with the labels that each got.

#476 [vcpkg_from_github] Document USE_TARBALL_API.
  vcpkg/maintainers/functions/vcpkg_from_github.md
Labels: do-not-merge, review-team-triage

#475 Fix cyclonedx docs link software-bill-of-materials.md
  vcpkg/reference/software-bill-of-materials.md
Labels: do-not-merge, review-team-triage

#470 Update binary-caching-nuget.md
  vcpkg/consume/binary-caching-nuget.md
Labels: do-not-merge, review-team-triage

#478 Add warning regarding github vcpkg binary cache removal
  vcpkg/consume/binary-caching-github-actions-cache.md
Labels: do-not-merge, review-team-triage

#479 Remove references to GitHub Actions Cache and the `x-gha` provider
  .gitignore
  includes/removed.md
  vcpkg/TOC.yml
  vcpkg/concepts/continuous-integration.md
  vcpkg/consume/binary-caching-default.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-github-packages.md
  vcpkg/consume/binary-caching-local.md
  vcpkg/consume/binary-caching-nuget.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/consume/third-party-authentication.nuget.md
  vcpkg/github-integration.md
  vcpkg/produce/test-registry-ports-gha.md
  vcpkg/reference/binarycaching.md
  vcpkg/users/binarycaching.md
  vcpkg/users/config-environment.md
Labels: do-not-merge, needs-human-review, review-team-triage

#480 Push to live 5/25
  .gitignore
  includes/removed.md
  vcpkg/TOC.yml
  vcpkg/concepts/continuous-integration.md
  vcpkg/consume/binary-caching-default.md
  vcpkg/consume/binary-caching-github-actions-cache.md
  vcpkg/consume/binary-caching-github-packages.md
  vcpkg/consume/binary-caching-local.md
  vcpkg/consume/binary-caching-nuget.md
  vcpkg/consume/binary-caching-overview.md
  vcpkg/consume/third-party-authentication.nuget.md
  vcpkg/github-integration.md
  vcpkg/maintainers/functions/vcpkg_from_github.md
  vcpkg/produce/test-registry-ports-gha.md
  vcpkg/reference/binarycaching.md
  vcpkg/reference/software-bill-of-materials.md
  vcpkg/users/binarycaching.md
  vcpkg/users/config-environment.md
Labels: do-not-merge

#486 Fix typo
  vcpkg/concepts/supported-hosts.md
Labels: do-not-merge, review-team-triage

#489 Remove notices that x-add-version requires a commit first.
  vcpkg/concepts/registries.md
  vcpkg/contributing/maintainer-guide.md
  vcpkg/produce/publish-to-a-git-registry.md
Labels: do-not-merge, review-team-triage
